create table country
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    continent varchar(4000)
);

create table author
(
    id                   bigint generated by default as identity
        primary key,
    name                 varchar(255),
    surname varchar(255),
    country_id     bigint references country,
);

create table book
(
    id              bigint generated by default as identity
        primary key,
    name            varchar(255),
    category           varchar(255),
    available_copies        integer,
    author_id     bigint references author,
    rented          boolean default false
);

create table book_users
(
    username                   varchar(255)
        primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table wish_list
(
    id            bigint generated by default as identity
        primary key,
    user_username varchar(255) references shop_users,
);

create table shopping_cart_products
(
    wish_list_id bigint references wish_list on delete cascade,
    books_id      bigint references book on delete cascade,
    primary key (wish_list_id, books_id)
);


create unique index idx_user_username_password on book_users (username, password);
create unique index idx_user_username on book_users (username);
create unique index idx_user_role on book_users (role);
